# Generated by Django 5.0.3 on 2024-03-10 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.FloatField()),
                ('village', models.CharField(max_length=255)),
                ('crop_grown', models.CharField(max_length=100)),
                ('sowing_date', models.DateField()),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.farmer')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_after_sowing', models.PositiveIntegerField()),
                ('fertiliser', models.CharField(max_length=100)),
                ('quantity', models.FloatField()),
                ('quantity_unit', models.CharField(max_length=10)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.farm')),
            ],
        ),
    ]
